# Brewfile
# Just run `brew tap homebrew/boneyard && brew bundle` in the same directory to have it run
#
# Need Homebrew?
# Run `ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`
# Or on a Linux box, run `ruby -e "$(wget -O- https://raw.github.com/Homebrew/linuxbrew/go/install)"`

tap 'caskroom/cask'

install 'ag'
install 'autoconf'
install 'autojump'
install 'automake'
install 'caskroom/cask/brew-cask'
install 'cloc'
install 'cmake'
install 'freetype'
install 'git'
install 'graphicsmagick'
install 'hub'
install 'imagemagick'
install 'jpeg'
install 'libpng'
install 'libtool'
install 'mercurial'
install 'node'
install 'pkg-config'
install 'pngquant'
install 'pow'
install 'rbenv'
install 'vim'
install 'wget'
install 'xz'
install 'zsh'

cask install 'colorpicker-skalacolor'
cask install 'dropbox'
cask install 'fantastical'
cask install 'firefox'
cask install 'flux'
cask install 'google-chrome'
cask install 'imageoptim'
cask install 'iterm2'
cask install 'jadengeller-helium'
cask install 'kaleidoscope'
cask install 'keepingyouawake'
cask install 'licecap'
cask install 'mailbox'
cask install 'slack'
cask install 'spotify'
cask install 'transmission'
cask install 'vlc'
