cask_args appdir: '/Applications'

tap 'github/gh'
tap 'homebrew/bundle'
tap 'homebrew/homebrew-cask'
tap 'homebrew/cask-versions'
tap 'homebrew/science'

brew 'ag'
brew 'autoconf'
brew 'autoenv'
brew 'autojump'
brew 'automake'
brew 'bfg'
brew 'cloc'
brew 'cmake'
brew 'coreutils'
brew 'fasd'
brew 'fd'
brew 'giflossy'
brew 'git'
brew 'gh'
brew 'gpg2'
brew 'htop'
brew 'mas'
brew 'mercurial'
brew 'node'
brew 'pinentry-mac'
brew 'pow'
brew 'reattach-to-user-namespace'
brew 'ruby'
brew 'shellcheck'
brew 'vim', args: ['with-lua']
brew 'wget'
brew 'wifi-password'
brew 'xz'
brew 'youtube-dl'
brew 'zsh'

cask '1password'
cask 'bartender'
cask 'Caskroom/cask/java'
cask 'dropbox'
cask 'imageoptim'
cask 'iterm2-beta'
cask 'keepingyouawake'
