#!/bin/bash
 
echo "Title of post:"
read title
 
 
dateStr=$(date +%Y'-'%m'-'%d'-')                          # Current date
blogFolder=~/Repos/daneden.me/_posts
YAML=$'---
layout: post
title: '$title'
---'                                                      # YAML matter at top
of blog post
lowercase=$(echo "$title" | tr '[:upper:]' '[:lower:]')
formattedTitle=${lowercase// /-}
echo $formattedTitle
newFile=$dateStr$formattedTitle'.markdown'
 
echo "$YAML" > $blogFolder/$newFile                       # Create post in
correct folder
 
vim $newFile
